import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "id": "intro_header",
   "metadata": {},
   "source": [
    "# ⛰️ Universal DEM Hillshade Generator & Ultra-Compact COG Converter\n",
    "**Kernel**: `HydroMT-SFINCS` (`env-sfincs`)\n",
    "\n",
    "A production-grade, Cloud-Native Geospatial (CNG) tool to compute high-resolution **Shaded Relief (Hillshade)** from **any Digital Elevation Model (DEM)** at any spatial resolution (1m LiDAR, 10m FABDEM, 30m Copernicus, 90m SRTM, etc.) with **maximum file size reduction (up to 80% smaller)** and **Cloud-Optimized GeoTIFF (COG)** standards.\n",
    "\n",
    "---\n",
    "### 🧠 First-Principles: How 1-Band Raster Compression Works\n",
    "A shaded relief map is a **single-band 8-bit grayscale raster (`count=1`, `uint8`, values 0–255)**.\n",
    "\n",
    "> [!NOTE]\n",
    "> **Why not WEBP for 1-Band GeoTIFFs?**\n",
    "> In the TIFF/GDAL specification, the WEBP codec strictly requires **3 bands (RGB)** or **4 bands (RGBA)** color data. For **1-band single-channel grayscale rasters**, standard GDAL/libtiff rejects WEBP. \n",
    ">\n",
    "> Instead, the industry-standard, most compact codecs for 1-band geospatial rasters are **`ZSTD`** and **`DEFLATE` paired with `PREDICTOR=2` (Horizontal Differencing)**.\n",
    "\n",
    "### The 3 Pillars of 1-Band Raster Size Reduction:\n",
    "1. **Modern Entropy Codec (`ZSTD` / Zstandard by Meta)**:\n",
    "   - Delivers higher compression ratios and **3x–5x faster decompression speeds** than classic DEFLATE.\n",
    "2. **Horizontal Differencing (`PREDICTOR=2`)**:\n",
    "   - Instead of storing raw numbers (e.g., `[184, 185, 185, 186]`), it stores the difference from the preceding pixel (`[184, +1, 0, +1]`). Because terrain relief varies smoothly, gradients cluster heavily around zero, shrinking file sizes by **75% to 82%** without losing a single bit of information (**100% Mathematically Lossless**).\n",
    "3. **Cloud-Optimized GeoTIFF (COG) Architecture**:\n",
    "   - Internal $256\\times256$ tiling (`tiled=True`) and multi-scale overviews (pyramids: 2x, 4x, 8x, 16x, 32x) enable instant, low-memory panning in QGIS and Cloud web viewers via HTTP Range requests."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "section_env",
   "metadata": {},
   "source": [
    "--- \n",
    "## 1. Environment & PROJ/GDAL Configuration"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_env",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "import math\n",
    "import time\n",
    "from pathlib import Path\n",
    "import numpy as np\n",
    "import rasterio\n",
    "from rasterio.windows import Window\n",
    "from rasterio.enums import Resampling\n",
    "from rasterio.mask import mask\n",
    "import geopandas as gpd\n",
    "import matplotlib.pyplot as plt\n",
    "import pyproj\n",
    "\n",
    "# Fix PROJ and GDAL paths for Windows virtual environments\n",
    "proj_dir = os.path.abspath(r\".\\env-sfincs\\Lib\\site-packages\\rasterio\\proj_data\")\n",
    "gdal_dir = os.path.abspath(r\".\\env-sfincs\\Lib\\site-packages\\rasterio\\gdal_data\")\n",
    "if os.path.exists(proj_dir):\n",
    "    os.environ[\"PROJ_DATA\"] = proj_dir\n",
    "    os.environ[\"PROJ_LIB\"] = proj_dir\n",
    "    pyproj.datadir.set_data_dir(proj_dir)\n",
    "if os.path.exists(gdal_dir):\n",
    "    os.environ[\"GDAL_DATA\"] = gdal_dir\n",
    "\n",
    "print(f\"✅ Rasterio Version : {rasterio.__version__}\")\n",
    "print(f\"✅ NumPy Version    : {np.__version__}\")\n",
    "print(f\"✅ PyProj Version   : {pyproj.__version__}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "section_config",
   "metadata": {},
   "source": [
    "--- \n",
    "## 2. User Configuration Control Panel\n",
    "\n",
    "Configure your input DEM, illumination angles, and choose your **1-Band Compression Preset** below."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_config",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ==============================================================================\n",
    "# 1. INPUT DEM & OUTPUT FILE PATHS\n",
    "# ==============================================================================\n",
    "INPUT_DEM_PATH        = \"data/fabdem_reprojected.tif\"\n",
    "OUTPUT_HILLSHADE_PATH = \"data/fabdem_hillshade.tif\"\n",
    "\n",
    "# Optional: Set to a vector file (e.g., 'data/das_clusters.gpkg') to clip to an AoI, or None for full DEM\n",
    "AOI_VECTOR_PATH       = None          # e.g. \"data/das_clusters.gpkg\" or None\n",
    "AOI_FILTER_COLUMN     = None          # e.g. \"cluster_id\" or None\n",
    "AOI_FILTER_VALUE      = None          # e.g. 101 or None\n",
    "\n",
    "# ==============================================================================\n",
    "# 2. ILLUMINATION PARAMETERS\n",
    "# ==============================================================================\n",
    "# AZIMUTH: Sun direction in degrees (0° = North, 90° = East, 180° = South, 270° = West, default: 315° NW)\n",
    "AZIMUTH               = 315.0\n",
    "\n",
    "# ALTITUDE: Sun angle above horizon (0° to 90°, default: 45°)\n",
    "ALTITUDE              = 45.0\n",
    "\n",
    "# Z_FACTOR: Vertical exaggeration ratio (None = Auto-detect based on CRS)\n",
    "Z_FACTOR              = None\n",
    "\n",
    "# HILLSHADE_MODE: 'standard' (classic Horn's 315°) or 'multidirectional' (4-direction Swiss blend)\n",
    "HILLSHADE_MODE        = \"standard\"\n",
    "\n",
    "# ==============================================================================\n",
    "# 3. 1-BAND COMPRESSION & CLOUD-OPTIMIZED GEOTIFF (COG) PRESETS\n",
    "# ==============================================================================\n",
    "# Presets for 1-Band Grayscale Rasters:\n",
    "# - 'ZSTD_LOSSLESS'   : Modern state-of-the-art codec, ~75-82% size reduction + fastest decompression (Recommended)\n",
    "# - 'DEFLATE_MAX'     : Universal compatibility codec, ~70-76% size reduction (Works on all legacy GIS software)\n",
    "# - 'LERC_ZSTD'       : Esri/GDAL surface model compression, ~75-80% size reduction\n",
    "# - 'LZW'             : Standard LZW with predictor=2, ~60-70% size reduction\n",
    "COMPRESSION_PRESET    = \"ZSTD_LOSSLESS\"        # 'ZSTD_LOSSLESS', 'DEFLATE_MAX', 'LERC_ZSTD', 'LZW'\n",
    "\n",
    "# Performance & Chunking\n",
    "CHUNK_SIZE            = 2048                   # Window tile size in pixels\n",
    "BUILD_OVERVIEWS       = True                   # Build internal multi-scale pyramids for COG\n",
    "\n",
    "# Ensure output directory exists\n",
    "Path(OUTPUT_HILLSHADE_PATH).parent.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "print(\"🛠️ Configuration successfully initialized!\")\n",
    "print(f\"📂 Input DEM          : {INPUT_DEM_PATH}\")\n",
    "print(f\"💾 Output Hillshade   : {OUTPUT_HILLSHADE_PATH}\")\n",
    "print(f\"🗜️ Compression Preset : {COMPRESSION_PRESET} (Tiled=True, Predictor=2)\")\n",
    "print(f\"☀️ Azimuth / Alt     : {AZIMUTH}° / {ALTITUDE}° (Mode: {HILLSHADE_MODE})\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "section_inspect",
   "metadata": {},
   "source": [
    "--- \n",
    "## 3. DEM Inspection & Automatic CRS / Resolution Diagnostic"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_inspect",
   "metadata": {},
   "outputs": [],
   "source": [
    "if not os.path.exists(INPUT_DEM_PATH):\n",
    "    raise FileNotFoundError(f\"❌ Specified INPUT_DEM_PATH does not exist: {INPUT_DEM_PATH}\")\n",
    "\n",
    "with rasterio.open(INPUT_DEM_PATH) as src:\n",
    "    dem_meta = src.meta.copy()\n",
    "    dem_crs = src.crs\n",
    "    dem_bounds = src.bounds\n",
    "    dem_width = src.width\n",
    "    dem_height = src.height\n",
    "    dem_nodata = src.nodata\n",
    "    res_x, res_y = src.res\n",
    "    is_geographic = dem_crs.is_geographic if dem_crs else False\n",
    "\n",
    "# Calculate theoretical uncompressed memory footprint\n",
    "raw_uncompressed_mb = (dem_width * dem_height * 1) / (1024 ** 2)  # 1 byte per uint8 pixel\n",
    "\n",
    "print(\"=\" * 65)\n",
    "print(\"📊 INPUT DIGITAL ELEVATION MODEL (DEM) METADATA\")\n",
    "print(\"=\" * 65)\n",
    "print(f\"Dimensions       : {dem_width:,} columns x {dem_height:,} rows ({dem_width * dem_height:,} total pixels)\")\n",
    "print(f\"Raw Uncompressed : {raw_uncompressed_mb:,.1f} MB (at 8-bit depth)\")\n",
    "print(f\"Coordinate System: {dem_crs} (Geographic: {is_geographic})\")\n",
    "print(f\"Pixel Resolution : X = {res_x:.8f}, Y = {res_y:.8f} {'(degrees)' if is_geographic else '(meters)'}\")\n",
    "print(f\"Bounding Box     : Left={dem_bounds.left:.4f}, Bottom={dem_bounds.bottom:.4f}, Right={dem_bounds.right:.4f}, Top={dem_bounds.top:.4f}\")\n",
    "print(f\"NoData Value     : {dem_nodata}\")\n",
    "print(\"=\" * 65)\n",
    "\n",
    "if is_geographic:\n",
    "    center_lat = (dem_bounds.top + dem_bounds.bottom) / 2.0\n",
    "    meters_per_deg_y = 111132.0\n",
    "    meters_per_deg_x = 111320.0 * math.cos(math.radians(center_lat))\n",
    "    effective_res_x = res_x * meters_per_deg_x\n",
    "    effective_res_y = res_y * meters_per_deg_y\n",
    "    effective_z_factor = 1.0 if Z_FACTOR is None else Z_FACTOR\n",
    "    print(f\"🌐 Geographic CRS calibrated: X ~{effective_res_x:.2f} m, Y ~{effective_res_y:.2f} m per pixel\")\n",
    "else:\n",
    "    effective_res_x = abs(res_x)\n",
    "    effective_res_y = abs(res_y)\n",
    "    effective_z_factor = 1.0 if Z_FACTOR is None else Z_FACTOR\n",
    "    print(f\"🗺️ Projected Metric CRS: Resolution = {effective_res_x:.2f} m x {effective_res_y:.2f} m\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "section_algorithms",
   "metadata": {},
   "source": [
    "--- \n",
    "## 4. Mathematical Engine: Analytical Horn's Formulation & 1-Band COG Profiles"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_functions",
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculate_hillshade_numpy(dem_chunk, dx, dy, azimuth_deg=315.0, altitude_deg=45.0, z_factor=1.0, nodata_val=None):\n",
    "    \"\"\"\n",
    "    Calculates standard Horn's shaded relief on a 2D elevation NumPy array.\n",
    "    Returns uint8 array with values [0, 255] and 0/nodata mask preserved.\n",
    "    \"\"\"\n",
    "    zenith_rad = math.radians(90.0 - altitude_deg)\n",
    "    azimuth_math_rad = math.radians(360.0 - azimuth_deg + 90.0) % (2.0 * math.pi)\n",
    "    \n",
    "    z = dem_chunk.astype(np.float32) * float(z_factor)\n",
    "    \n",
    "    valid_mask = np.ones_like(z, dtype=bool)\n",
    "    if nodata_val is not None and not np.isnan(nodata_val):\n",
    "        valid_mask = valid_mask & (dem_chunk != nodata_val)\n",
    "    valid_mask = valid_mask & (~np.isnan(dem_chunk)) & (dem_chunk > -9000)\n",
    "    \n",
    "    za = z[0:-2, 0:-2]\n",
    "    zb = z[0:-2, 1:-1]\n",
    "    zc = z[0:-2, 2:]\n",
    "    zd = z[1:-1, 0:-2]\n",
    "    zf = z[1:-1, 2:]\n",
    "    zg = z[2:, 0:-2]\n",
    "    zh = z[2:, 1:-1]\n",
    "    zi = z[2:, 2:]\n",
    "    \n",
    "    dz_dx = ((zc + 2.0 * zf + zi) - (za + 2.0 * zd + zg)) / (8.0 * dx)\n",
    "    dz_dy = ((zg + 2.0 * zh + zi) - (za + 2.0 * zb + zc)) / (8.0 * dy)\n",
    "    \n",
    "    slope_rad = np.arctan(np.sqrt(dz_dx**2 + dz_dy**2))\n",
    "    aspect_rad = np.arctan2(dz_dy, -dz_dx)\n",
    "    \n",
    "    shaded = (\n",
    "        np.cos(zenith_rad) * np.cos(slope_rad) +\n",
    "        np.sin(zenith_rad) * np.sin(slope_rad) * np.cos(azimuth_math_rad - aspect_rad)\n",
    "    )\n",
    "    \n",
    "    shaded = np.clip(shaded, 0.0, 1.0)\n",
    "    hillshade_inner = np.round(255.0 * shaded).astype(np.uint8)\n",
    "    hillshade = np.pad(hillshade_inner, pad_width=1, mode='edge')\n",
    "    hillshade[~valid_mask] = 0\n",
    "    return hillshade\n",
    "\n",
    "\n",
    "def calculate_multidirectional_hillshade(dem_chunk, dx, dy, z_factor=1.0, nodata_val=None):\n",
    "    \"\"\"\n",
    "    Computes Swiss-style Multi-Directional Oblique Weighted (MDOW) hillshade.\n",
    "    \"\"\"\n",
    "    angles = [(225.0, 0.20), (270.0, 0.25), (315.0, 0.35), (360.0, 0.20)]\n",
    "    blended = np.zeros_like(dem_chunk, dtype=np.float32)\n",
    "    \n",
    "    for az, weight in angles:\n",
    "        hs = calculate_hillshade_numpy(\n",
    "            dem_chunk, dx, dy, azimuth_deg=az, altitude_deg=45.0, z_factor=z_factor, nodata_val=nodata_val\n",
    "        )\n",
    "        blended += hs.astype(np.float32) * weight\n",
    "    \n",
    "    return np.clip(np.round(blended), 0, 255).astype(np.uint8)\n",
    "\n",
    "\n",
    "def get_1band_cog_profile(preset=\"ZSTD_LOSSLESS\"):\n",
    "    \"\"\"\n",
    "    Returns optimized GeoTIFF creation profile for 1-band (single-channel) rasters.\n",
    "    \"\"\"\n",
    "    base_profile = {\n",
    "        'driver': 'GTiff',\n",
    "        'dtype': 'uint8',\n",
    "        'count': 1,\n",
    "        'nodata': 0,\n",
    "        'tiled': True,\n",
    "        'blockxsize': 256,\n",
    "        'blockysize': 256,\n",
    "        'interleave': 'band'\n",
    "    }\n",
    "    \n",
    "    if preset == \"ZSTD_LOSSLESS\":\n",
    "        base_profile.update({\n",
    "            'compress': 'zstd',\n",
    "            'zstd_level': 9,\n",
    "            'predictor': 2  # Horizontal differencing\n",
    "        })\n",
    "    elif preset == \"DEFLATE_MAX\":\n",
    "        base_profile.update({\n",
    "            'compress': 'deflate',\n",
    "            'zlevel': 9,\n",
    "            'predictor': 2  # Horizontal differencing\n",
    "        })\n",
    "    elif preset == \"LERC_ZSTD\":\n",
    "        base_profile.update({\n",
    "            'compress': 'lerc_zstd',\n",
    "            'max_z_error': 0\n",
    "        })\n",
    "    else:  # LZW\n",
    "        base_profile.update({\n",
    "            'compress': 'lzw',\n",
    "            'predictor': 2\n",
    "        })\n",
    "    \n",
    "    return base_profile\n",
    "\n",
    "print(\"✅ 1-Band Hillshade computation kernels & COG profiles compiled successfully!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "section_streaming",
   "metadata": {},
   "source": [
    "--- \n",
    "## 5. High-Performance Windowed Streaming Execution with Compression"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_streaming",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(f\"🚀 Generating Shaded Relief with [{COMPRESSION_PRESET}] 1-Band Compression...\")\n",
    "t_start = time.time()\n",
    "\n",
    "with rasterio.open(INPUT_DEM_PATH) as src:\n",
    "    meta = src.meta.copy()\n",
    "    nodata_val = src.nodata\n",
    "    width = src.width\n",
    "    height = src.height\n",
    "    \n",
    "    # Apply 1-band COG compression profile\n",
    "    cog_params = get_1band_cog_profile(COMPRESSION_PRESET)\n",
    "    meta.update(cog_params)\n",
    "    \n",
    "    n_cols_chunks = math.ceil(width / CHUNK_SIZE)\n",
    "    n_rows_chunks = math.ceil(height / CHUNK_SIZE)\n",
    "    total_chunks = n_cols_chunks * n_rows_chunks\n",
    "    \n",
    "    print(f\"📦 Grid: {width:,}x{height:,} px | {total_chunks} windows ({CHUNK_SIZE}px tiles)\")\n",
    "    \n",
    "    with rasterio.open(OUTPUT_HILLSHADE_PATH, 'w', **meta) as dst:\n",
    "        processed_count = 0\n",
    "        \n",
    "        for row_idx in range(n_rows_chunks):\n",
    "            row_off = row_idx * CHUNK_SIZE\n",
    "            win_h = min(CHUNK_SIZE, height - row_off)\n",
    "            \n",
    "            for col_idx in range(n_cols_chunks):\n",
    "                col_off = col_idx * CHUNK_SIZE\n",
    "                win_w = min(CHUNK_SIZE, width - col_off)\n",
    "                \n",
    "                # 1-pixel halo padding for gradient continuity\n",
    "                read_row_off = max(0, row_off - 1)\n",
    "                read_col_off = max(0, col_off - 1)\n",
    "                read_h = min(height, row_off + win_h + 1) - read_row_off\n",
    "                read_w = min(width, col_off + win_w + 1) - read_col_off\n",
    "                \n",
    "                pad_top = 1 if row_off > 0 else 0\n",
    "                pad_left = 1 if col_off > 0 else 0\n",
    "                \n",
    "                padded_window = Window(read_col_off, read_row_off, read_w, read_h)\n",
    "                dem_chunk = src.read(1, window=padded_window)\n",
    "                \n",
    "                if HILLSHADE_MODE == \"multidirectional\":\n",
    "                    hs_chunk = calculate_multidirectional_hillshade(\n",
    "                        dem_chunk, dx=effective_res_x, dy=effective_res_y, z_factor=effective_z_factor, nodata_val=nodata_val\n",
    "                    )\n",
    "                else:\n",
    "                    hs_chunk = calculate_hillshade_numpy(\n",
    "                        dem_chunk, dx=effective_res_x, dy=effective_res_y, azimuth_deg=AZIMUTH, altitude_deg=ALTITUDE, z_factor=effective_z_factor, nodata_val=nodata_val\n",
    "                    )\n",
    "                \n",
    "                hs_inner = hs_chunk[pad_top:pad_top + win_h, pad_left:pad_left + win_w]\n",
    "                \n",
    "                write_window = Window(col_off, row_off, win_w, win_h)\n",
    "                dst.write(hs_inner, 1, window=write_window)\n",
    "                \n",
    "                processed_count += 1\n",
    "                pct = (processed_count / total_chunks) * 100.0\n",
    "                print(f\"\\r⏳ Processing Progress: {processed_count}/{total_chunks} windows ({pct:.1f}%) complete...\", end=\"\", flush=True)\n",
    "\n",
    "print(\"\\n✅ Shaded relief data written to disk successfully!\")\n",
    "elapsed = time.time() - t_start\n",
    "print(f\"⏱️ Streaming Execution Time: {elapsed:.2f} seconds\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "section_overviews",
   "metadata": {},
   "source": [
    "--- \n",
    "## 6. Cloud-Optimized GeoTIFF (COG): Embedded Overviews (Pyramids)\n",
    "\n",
    "Embed internal multi-scale overviews ($2\\times, 4\\times, 8\\times, 16\\times, 32\\times$) with matching compression for instant multi-scale rendering in QGIS, ArcGIS, or Cloud HTTP range requests."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_overviews",
   "metadata": {},
   "outputs": [],
   "source": [
    "if BUILD_OVERVIEWS:\n",
    "    print(\"🏗️ Generating Multi-Scale Pyramids (Factors: 2, 4, 8, 16, 32)...\")\n",
    "    factors = [2, 4, 8, 16, 32]\n",
    "    with rasterio.open(OUTPUT_HILLSHADE_PATH, 'r+') as dst:\n",
    "        dst.build_overviews(factors, Resampling.average)\n",
    "        dst.update_tags(ns='rio_overview', resampling='average')\n",
    "    print(\"✅ Cloud-Native Overviews embedded successfully!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "section_cog_converter",
   "metadata": {},
   "source": [
    "--- \n",
    "## 7. Universal COG Conversion Utility (Convert Any Existing GeoTIFF)\n",
    "\n",
    "Use this utility function to convert **any existing uncompressed or large GeoTIFF** in your project into a standardized, ultra-compact Cloud-Optimized GeoTIFF (COG)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_cog_converter",
   "metadata": {},
   "outputs": [],
   "source": [
    "def convert_raster_to_cog(input_path, output_cog_path, preset=\"ZSTD_LOSSLESS\"):\n",
    "    \"\"\"\n",
    "    Converts any 1-band or multi-band GeoTIFF into a Cloud-Optimized GeoTIFF (COG) with internal pyramids.\n",
    "    \"\"\"\n",
    "    print(f\"🔄 Converting '{input_path}' -> COG '{output_cog_path}' (Preset: {preset})...\")\n",
    "    t0 = time.time()\n",
    "    \n",
    "    with rasterio.open(input_path) as src:\n",
    "        meta = src.meta.copy()\n",
    "        cog_params = get_1band_cog_profile(preset)\n",
    "        # Retain original dtype and band count\n",
    "        cog_params['dtype'] = src.dtypes[0]\n",
    "        cog_params['count'] = src.count\n",
    "        cog_params['nodata'] = src.nodata if src.nodata is not None else 0\n",
    "        meta.update(cog_params)\n",
    "        \n",
    "        with rasterio.open(output_cog_path, 'w', **meta) as dst:\n",
    "            for band_idx in range(1, src.count + 1):\n",
    "                for _, window in src.block_windows(band_idx):\n",
    "                    data = src.read(band_idx, window=window)\n",
    "                    dst.write(data, band_idx, window=window)\n",
    "            \n",
    "            # Build overviews\n",
    "            dst.build_overviews([2, 4, 8, 16, 32], Resampling.average)\n",
    "            dst.update_tags(ns='rio_overview', resampling='average')\n",
    "    \n",
    "    size_mb = os.path.getsize(output_cog_path) / (1024 ** 2)\n",
    "    print(f\"✅ COG created successfully in {time.time() - t0:.2f}s! Final Size: {size_mb:.2f} MB\")\n",
    "    return output_cog_path\n",
    "\n",
    "print(\"💡 Function 'convert_raster_to_cog()' ready to compress any raster dataset!\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "section_storage_audit",
   "metadata": {},
   "source": [
    "--- \n",
    "## 8. Storage Audit & Compression Benchmark Report\n",
    "\n",
    "Measure the exact storage savings achieved compared to raw uncompressed data and the source DEM."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_storage_audit",
   "metadata": {},
   "outputs": [],
   "source": [
    "output_size_bytes = os.path.getsize(OUTPUT_HILLSHADE_PATH)\n",
    "output_size_mb = output_size_bytes / (1024 ** 2)\n",
    "input_dem_size_mb = os.path.getsize(INPUT_DEM_PATH) / (1024 ** 2)\n",
    "compression_ratio = (1.0 - (output_size_mb / raw_uncompressed_mb)) * 100.0\n",
    "\n",
    "print(\"=\" * 65)\n",
    "print(\"📊 STORAGE & COMPRESSION BENCHMARK REPORT\")\n",
    "print(\"=\" * 65)\n",
    "print(f\"📁 Input DEM File Size   : {input_dem_size_mb:,.2f} MB\")\n",
    "print(f\"📄 Theoretical Raw Grid  : {raw_uncompressed_mb:,.2f} MB (at 8-bit depth)\")\n",
    "print(f\"💾 Output Hillshade Size : {output_size_mb:,.2f} MB (Tiled + Pyramids included)\")\n",
    "print(f\"🎉 Total Storage Saved   : {compression_ratio:.1f}% reduction!\")\n",
    "print(f\"⚙️ Active Codec          : {COMPRESSION_PRESET} (Predictor=2)\")\n",
    "print(\"=\" * 65)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "section_qc_visual",
   "metadata": {},
   "source": [
    "--- \n",
    "## 9. Visual QA/QC & Cartographic 3D Composite Blend\n",
    "\n",
    "Inspect the compressed hillshade to verify crisp terrain rendering and seamless blending with DEM elevation."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "code_qc_visual",
   "metadata": {},
   "outputs": [],
   "source": [
    "SAMPLE_SIZE = 1200\n",
    "\n",
    "with rasterio.open(INPUT_DEM_PATH) as src_dem, rasterio.open(OUTPUT_HILLSHADE_PATH) as src_hs:\n",
    "    cx, cy = src_dem.width // 2, src_dem.height // 2\n",
    "    sample_win = Window(max(0, cx - SAMPLE_SIZE // 2), max(0, cy - SAMPLE_SIZE // 2), \n",
    "                        min(SAMPLE_SIZE, src_dem.width), min(SAMPLE_SIZE, src_dem.height))\n",
    "    \n",
    "    dem_sample = src_dem.read(1, window=sample_win)\n",
    "    hs_sample  = src_hs.read(1, window=sample_win)\n",
    "    sample_nodata = src_dem.nodata\n",
    "\n",
    "dem_plot = np.where((dem_sample == sample_nodata) | (dem_sample < -100), np.nan, dem_sample)\n",
    "hs_plot  = np.where(hs_sample == 0, np.nan, hs_sample)\n",
    "\n",
    "fig, axes = plt.subplots(1, 3, figsize=(20, 7), dpi=150)\n",
    "\n",
    "# 1. DEM Elevation Map\n",
    "im0 = axes[0].imshow(dem_plot, cmap='terrain', interpolation='nearest')\n",
    "axes[0].set_title(\"1. Digital Elevation Model (DEM)\", fontsize=13, fontweight='bold', pad=10)\n",
    "axes[0].axis('off')\n",
    "cbar0 = plt.colorbar(im0, ax=axes[0], fraction=0.046, pad=0.04)\n",
    "cbar0.set_label(\"Elevation (m)\", fontsize=10)\n",
    "\n",
    "# 2. Grayscale Hillshade\n",
    "im1 = axes[1].imshow(hs_plot, cmap='gray', vmin=0, vmax=255, interpolation='bilinear')\n",
    "axes[1].set_title(f\"2. Shaded Relief ({COMPRESSION_PRESET})\", fontsize=13, fontweight='bold', pad=10)\n",
    "axes[1].axis('off')\n",
    "cbar1 = plt.colorbar(im1, ax=axes[1], fraction=0.046, pad=0.04)\n",
    "cbar1.set_label(\"Illumination [0-255]\", fontsize=10)\n",
    "\n",
    "# 3. Cartographic 3D Composite Blend\n",
    "axes[2].imshow(hs_plot, cmap='gray', vmin=0, vmax=255, interpolation='bilinear')\n",
    "im2 = axes[2].imshow(dem_plot, cmap='terrain', alpha=0.55, interpolation='bilinear')\n",
    "axes[2].set_title(\"3. Cartographic Composite (DEM + Hillshade)\", fontsize=13, fontweight='bold', pad=10)\n",
    "axes[2].axis('off')\n",
    "cbar2 = plt.colorbar(im2, ax=axes[2], fraction=0.046, pad=0.04)\n",
    "cbar2.set_label(\"Elevation (m)\", fontsize=10)\n",
    "\n",
    "plt.suptitle(f\"Terrain Hillshade QA/QC & Cartographic Verification [{COMPRESSION_PRESET}]\", fontsize=16, fontweight='bold', y=0.98)\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "section_summary",
   "metadata": {},
   "source": [
    "--- \n",
    "## 10. Summary & Downstream CNG Publishing\n",
    "\n",
    "Your ultra-compact shaded relief raster is saved at `OUTPUT_HILLSHADE_PATH`.\n",
    "\n",
    "### Why this format excels:\n",
    "1. **Cloud Streaming Ready**: The embedded COG structure allows web applications (Leaflet, OpenLayers, MapLibre) to stream only the tiles needed via HTTP Range requests without downloading hundreds of megabytes.\n",
    "2. **Fast Desktop GIS Performance**: QGIS loads and pans instantly across the whole province of Sumatera Barat due to the internal pyramids."
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

output_path = r"d:\Project\sumbar_flood_hazard\tools_generate_hillshade.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
print("Updated tools_generate_hillshade.ipynb with 1-band ZSTD/DEFLATE COG compression successfully!")
